# Generated by Django 2.2 on 2022-01-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20220123_1715'),
        ('books', '0002_auto_20220129_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete='', related_name='books_uploaded', to='login.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='user_who_like',
            field=models.ManyToManyField(null=True, related_name='liked_books', to='login.User'),
        ),
    ]
